m = {'Tacubaya': {'Observatorio': 3,
              'Juanacatlán': 7,
              'Chapultepec': 12,
              'Sevilla': 13,
              'Insurgentes': 13,
              'Cuauhtémoc': 11,
              'Balderas': 10,
              'Juárez': 11,
              'Niños Héroes': 9,
              'Hospital General': 7,
              'Centro Médico': 6,
              'Etiopía': 8,
              'Eugenia': 10,
              'División del Norte': 12,
              'Zapata': 14,
              'Coyoacán': 17,
              'Viveros': 19,
              'Miguel Ángel de Quevedo': 20,
              'Copilco': 23,
              'Universidad': 26,
              'Polanco': 5,
              'Auditorio': 4,
              'Constituyentes': 1,
              'San Pedro de los Pinos': 2,
              'San Antonio': 3,
              'Mixcoac': 5,
              'Barranca del Muerto': 7,
              'Patriotismo': 2,
              'Chilpancingo': 4,
              'Lázaro Cárdenas': 8,
              'Insurgentes Sur': 7,
              'Hospital 20 de Noviembre': 9,
              'Parque de los Venados': 12,
              'Eje Central': 16},
 'Juanacatlán': {'Observatorio': 10,
                 'Tacubaya': 7,
                 'Chapultepec': 5,
                 'Sevilla': 6,
                 'Insurgentes': 8,
                 'Cuauhtémoc': 10,
                 'Balderas': 11,
                 'Juárez': 12,
                 'Niños Héroes': 12,
                 'Hospital General': 14,
                 'Centro Médico': 13,
                 'Etiopía': 15,
                 'Eugenia': 17,
                 'División del Norte': 19,
                 'Zapata': 21,
                 'Coyoacán': 24,
                 'Viveros': 26,
                 'Miguel Ángel de Quevedo': 27,
                 'Copilco': 30,
                 'Universidad': 33,
                 'Polanco': 12,
                 'Auditorio': 11,
                 'Constituyentes': 8,
                 'San Pedro de los Pinos': 9,
                 'San Antonio': 10,
                 'Mixcoac': 12,
                 'Barranca del Muerto': 14,
                 'Patriotismo': 9,
                 'Chilpancingo': 11,
                 'Lázaro Cárdenas': 15,
                 'Insurgentes Sur': 14,
                 'Hospital 20 de Noviembre': 16,
                 'Parque de los Venados': 19,
                 'Eje Central': 23},
 'Chapultepec': {'Observatorio': 15,
                 'Tacubaya': 12,
                 'Juanacatlán': 5,
                 'Sevilla': 1,
                 'Insurgentes': 3,
                 'Cuauhtémoc': 5,
                 'Balderas': 6,
                 'Juárez': 7,
                 'Niños Héroes': 7,
                 'Hospital General': 9,
                 'Centro Médico': 10,
                 'Etiopía': 12,
                 'Eugenia': 14,
                 'División del Norte': 16,
                 'Zapata': 18,
                 'Coyoacán': 21,
                 'Viveros': 23,
                 'Miguel Ángel de Quevedo': 24,
                 'Copilco': 27,
                 'Universidad': 30,
                 'Polanco': 17,
                 'Auditorio': 16,
                 'Constituyentes': 13,
                 'San Pedro de los Pinos': 14,
                 'San Antonio': 15,
                 'Mixcoac': 17,
                 'Barranca del Muerto': 19,
                 'Patriotismo': 14,
                 'Chilpancingo': 12,
                 'Lázaro Cárdenas': 12,
                 'Insurgentes Sur': 19,
                 'Hospital 20 de Noviembre': 21,
                 'Parque de los Venados': 24,
                 'Eje Central': 28},
 'Sevilla': {'Observatorio': 16,
             'Tacubaya': 13,
             'Juanacatlán': 6,
             'Chapultepec': 1,
             'Insurgentes': 2,
             'Cuauhtémoc': 4,
             'Balderas': 5,
             'Juárez': 6,
             'Niños Héroes': 6,
             'Hospital General': 8,
             'Centro Médico': 9,
             'Etiopía': 11,
             'Eugenia': 13,
             'División del Norte': 15,
             'Zapata': 17,
             'Coyoacán': 20,
             'Viveros': 22,
             'Miguel Ángel de Quevedo': 23,
             'Copilco': 26,
             'Universidad': 29,
             'Polanco': 18,
             'Auditorio': 17,
             'Constituyentes': 14,
             'San Pedro de los Pinos': 15,
             'San Antonio': 16,
             'Mixcoac': 18,
             'Barranca del Muerto': 20,
             'Patriotismo': 13,
             'Chilpancingo': 11,
             'Lázaro Cárdenas': 11,
             'Insurgentes Sur': 20,
             'Hospital 20 de Noviembre': 22,
             'Parque de los Venados': 25,
             'Eje Central': 29},
 'Insurgentes': {'Observatorio': 16,
                 'Tacubaya': 13,
                 'Juanacatlán': 8,
                 'Chapultepec': 3,
                 'Sevilla': 2,
                 'Cuauhtémoc': 2,
                 'Balderas': 3,
                 'Juárez': 4,
                 'Niños Héroes': 4,
                 'Hospital General': 6,
                 'Centro Médico': 7,
                 'Etiopía': 9,
                 'Eugenia': 11,
                 'División del Norte': 13,
                 'Zapata': 15,
                 'Coyoacán': 18,
                 'Viveros': 20,
                 'Miguel Ángel de Quevedo': 21,
                 'Copilco': 24,
                 'Universidad': 27,
                 'Polanco': 18,
                 'Auditorio': 17,
                 'Constituyentes': 14,
                 'San Pedro de los Pinos': 15,
                 'San Antonio': 16,
                 'Mixcoac': 18,
                 'Barranca del Muerto': 20,
                 'Patriotismo': 11,
                 'Chilpancingo': 9,
                 'Lázaro Cárdenas': 9,
                 'Insurgentes Sur': 20,
                 'Hospital 20 de Noviembre': 22,
                 'Parque de los Venados': 25,
                 'Eje Central': 29},
 'Cuauhtémoc': {'Observatorio': 14,
                'Tacubaya': 11,
                'Juanacatlán': 10,
                'Chapultepec': 5,
                'Sevilla': 4,
                'Insurgentes': 2,
                'Balderas': 1,
                'Juárez': 2,
                'Niños Héroes': 2,
                'Hospital General': 4,
                'Centro Médico': 5,
                'Etiopía': 7,
                'Eugenia': 9,
                'División del Norte': 11,
                'Zapata': 13,
                'Coyoacán': 16,
                'Viveros': 18,
                'Miguel Ángel de Quevedo': 19,
                'Copilco': 22,
                'Universidad': 25,
                'Polanco': 16,
                'Auditorio': 15,
                'Constituyentes': 12,
                'San Pedro de los Pinos': 13,
                'San Antonio': 14,
                'Mixcoac': 16,
                'Barranca del Muerto': 18,
                'Patriotismo': 9,
                'Chilpancingo': 7,
                'Lázaro Cárdenas': 7,
                'Insurgentes Sur': 18,
                'Hospital 20 de Noviembre': 20,
                'Parque de los Venados': 23,
                'Eje Central': 27},
 'Balderas': {'Observatorio': 13,
              'Tacubaya': 10,
              'Juanacatlán': 11,
              'Chapultepec': 6,
              'Sevilla': 5,
              'Insurgentes': 3,
              'Cuauhtémoc': 1,
              'Juárez': 1,
              'Niños Héroes': 1,
              'Hospital General': 3,
              'Centro Médico': 4,
              'Etiopía': 6,
              'Eugenia': 8,
              'División del Norte': 10,
              'Zapata': 12,
              'Coyoacán': 15,
              'Viveros': 17,
              'Miguel Ángel de Quevedo': 18,
              'Copilco': 21,
              'Universidad': 24,
              'Polanco': 15,
              'Auditorio': 14,
              'Constituyentes': 11,
              'San Pedro de los Pinos': 12,
              'San Antonio': 13,
              'Mixcoac': 15,
              'Barranca del Muerto': 17,
              'Patriotismo': 8,
              'Chilpancingo': 6,
              'Lázaro Cárdenas': 6,
              'Insurgentes Sur': 17,
              'Hospital 20 de Noviembre': 19,
              'Parque de los Venados': 22,
              'Eje Central': 26},
 'Juárez': {'Observatorio': 14,
            'Tacubaya': 11,
            'Juanacatlán': 12,
            'Chapultepec': 7,
            'Sevilla': 6,
            'Insurgentes': 4,
            'Cuauhtémoc': 2,
            'Balderas': 1,
            'Niños Héroes': 2,
            'Hospital General': 4,
            'Centro Médico': 5,
            'Etiopía': 7,
            'Eugenia': 9,
            'División del Norte': 11,
            'Zapata': 13,
            'Coyoacán': 16,
            'Viveros': 18,
            'Miguel Ángel de Quevedo': 19,
            'Copilco': 22,
            'Universidad': 25,
            'Polanco': 16,
            'Auditorio': 15,
            'Constituyentes': 12,
            'San Pedro de los Pinos': 13,
            'San Antonio': 14,
            'Mixcoac': 16,
            'Barranca del Muerto': 18,
            'Patriotismo': 9,
            'Chilpancingo': 7,
            'Lázaro Cárdenas': 7,
            'Insurgentes Sur': 18,
            'Hospital 20 de Noviembre': 20,
            'Parque de los Venados': 23,
            'Eje Central': 27},
 'Niños Héroes': {'Observatorio': 12,
                  'Tacubaya': 9,
                  'Juanacatlán': 12,
                  'Chapultepec': 7,
                  'Sevilla': 6,
                  'Insurgentes': 4,
                  'Cuauhtémoc': 2,
                  'Balderas': 1,
                  'Juárez': 2,
                  'Hospital General': 2,
                  'Centro Médico': 3,
                  'Etiopía': 5,
                  'Eugenia': 7,
                  'División del Norte': 9,
                  'Zapata': 11,
                  'Coyoacán': 14,
                  'Viveros': 16,
                  'Miguel Ángel de Quevedo': 17,
                  'Copilco': 20,
                  'Universidad': 23,
                  'Polanco': 14,
                  'Auditorio': 13,
                  'Constituyentes': 10,
                  'San Pedro de los Pinos': 11,
                  'San Antonio': 12,
                  'Mixcoac': 14,
                  'Barranca del Muerto': 16,
                  'Patriotismo': 7,
                  'Chilpancingo': 5,
                  'Lázaro Cárdenas': 5,
                  'Insurgentes Sur': 16,
                  'Hospital 20 de Noviembre': 18,
                  'Parque de los Venados': 21,
                  'Eje Central': 25},
 'Hospital General': {'Observatorio': 10,
                      'Tacubaya': 7,
                      'Juanacatlán': 14,
                      'Chapultepec': 9,
                      'Sevilla': 8,
                      'Insurgentes': 6,
                      'Cuauhtémoc': 4,
                      'Balderas': 3,
                      'Juárez': 4,
                      'Niños Héroes': 2,
                      'Centro Médico': 1,
                      'Etiopía': 3,
                      'Eugenia': 5,
                      'División del Norte': 7,
                      'Zapata': 9,
                      'Coyoacán': 12,
                      'Viveros': 14,
                      'Miguel Ángel de Quevedo': 15,
                      'Copilco': 18,
                      'Universidad': 21,
                      'Polanco': 12,
                      'Auditorio': 11,
                      'Constituyentes': 8,
                      'San Pedro de los Pinos': 9,
                      'San Antonio': 10,
                      'Mixcoac': 12,
                      'Barranca del Muerto': 14,
                      'Patriotismo': 5,
                      'Chilpancingo': 3,
                      'Lázaro Cárdenas': 3,
                      'Insurgentes Sur': 14,
                      'Hospital 20 de Noviembre': 16,
                      'Parque de los Venados': 19,
                      'Eje Central': 23},
 'Centro Médico': {'Observatorio': 9,
                   'Tacubaya': 6,
                   'Juanacatlán': 13,
                   'Chapultepec': 10,
                   'Sevilla': 9,
                   'Insurgentes': 7,
                   'Cuauhtémoc': 5,
                   'Balderas': 4,
                   'Juárez': 5,
                   'Niños Héroes': 3,
                   'Hospital General': 1,
                   'Etiopía': 2,
                   'Eugenia': 4,
                   'División del Norte': 6,
                   'Zapata': 8,
                   'Coyoacán': 11,
                   'Viveros': 13,
                   'Miguel Ángel de Quevedo': 14,
                   'Copilco': 17,
                   'Universidad': 20,
                   'Polanco': 11,
                   'Auditorio': 10,
                   'Constituyentes': 7,
                   'San Pedro de los Pinos': 8,
                   'San Antonio': 9,
                   'Mixcoac': 11,
                   'Barranca del Muerto': 13,
                   'Patriotismo': 4,
                   'Chilpancingo': 2,
                   'Lázaro Cárdenas': 2,
                   'Insurgentes Sur': 13,
                   'Hospital 20 de Noviembre': 15,
                   'Parque de los Venados': 18,
                   'Eje Central': 22},
 'Etiopía': {'Observatorio': 11,
             'Tacubaya': 8,
             'Juanacatlán': 15,
             'Chapultepec': 12,
             'Sevilla': 11,
             'Insurgentes': 9,
             'Cuauhtémoc': 7,
             'Balderas': 6,
             'Juárez': 7,
             'Niños Héroes': 5,
             'Hospital General': 3,
             'Centro Médico': 2,
             'Eugenia': 2,
             'División del Norte': 4,
             'Zapata': 6,
             'Coyoacán': 9,
             'Viveros': 11,
             'Miguel Ángel de Quevedo': 12,
             'Copilco': 15,
             'Universidad': 18,
             'Polanco': 13,
             'Auditorio': 12,
             'Constituyentes': 9,
             'San Pedro de los Pinos': 10,
             'San Antonio': 11,
             'Mixcoac': 13,
             'Barranca del Muerto': 15,
             'Patriotismo': 6,
             'Chilpancingo': 4,
             'Lázaro Cárdenas': 4,
             'Insurgentes Sur': 15,
             'Hospital 20 de Noviembre': 17,
             'Parque de los Venados': 20,
             'Eje Central': 24},
 'Eugenia': {'Observatorio': 13,
             'Tacubaya': 10,
             'Juanacatlán': 17,
             'Chapultepec': 14,
             'Sevilla': 13,
             'Insurgentes': 11,
             'Cuauhtémoc': 9,
             'Balderas': 8,
             'Juárez': 9,
             'Niños Héroes': 7,
             'Hospital General': 5,
             'Centro Médico': 4,
             'Etiopía': 2,
             'División del Norte': 2,
             'Zapata': 4,
             'Coyoacán': 7,
             'Viveros': 9,
             'Miguel Ángel de Quevedo': 10,
             'Copilco': 13,
             'Universidad': 16,
             'Polanco': 15,
             'Auditorio': 14,
             'Constituyentes': 11,
             'San Pedro de los Pinos': 12,
             'San Antonio': 13,
             'Mixcoac': 15,
             'Barranca del Muerto': 17,
             'Patriotismo': 8,
             'Chilpancingo': 6,
             'Lázaro Cárdenas': 6,
             'Insurgentes Sur': 17,
             'Hospital 20 de Noviembre': 19,
             'Parque de los Venados': 22,
             'Eje Central': 26},
 'División del Norte': {'Observatorio': 15,
                        'Tacubaya': 12,
                        'Juanacatlán': 19,
                        'Chapultepec': 16,
                        'Sevilla': 15,
                        'Insurgentes': 13,
                        'Cuauhtémoc': 11,
                        'Balderas': 10,
                        'Juárez': 11,
                        'Niños Héroes': 9,
                        'Hospital General': 7,
                        'Centro Médico': 6,
                        'Etiopía': 4,
                        'Eugenia': 2,
                        'Zapata': 2,
                        'Coyoacán': 5,
                        'Viveros': 7,
                        'Miguel Ángel de Quevedo': 8,
                        'Copilco': 11,
                        'Universidad': 14,
                        'Polanco': 17,
                        'Auditorio': 16,
                        'Constituyentes': 13,
                        'San Pedro de los Pinos': 14,
                        'San Antonio': 15,
                        'Mixcoac': 17,
                        'Barranca del Muerto': 19,
                        'Patriotismo': 10,
                        'Chilpancingo': 8,
                        'Lázaro Cárdenas': 8,
                        'Insurgentes Sur': 19,
                        'Hospital 20 de Noviembre': 21,
                        'Parque de los Venados': 24,
                        'Eje Central': 28},
 'Zapata': {'Observatorio': 17,
            'Tacubaya': 14,
            'Juanacatlán': 21,
            'Chapultepec': 18,
            'Sevilla': 17,
            'Insurgentes': 15,
            'Cuauhtémoc': 13,
            'Balderas': 12,
            'Juárez': 13,
            'Niños Héroes': 11,
            'Hospital General': 9,
            'Centro Médico': 8,
            'Etiopía': 6,
            'Eugenia': 4,
            'División del Norte': 2,
            'Coyoacán': 3,
            'Viveros': 5,
            'Miguel Ángel de Quevedo': 6,
            'Copilco': 9,
            'Universidad': 12,
            'Polanco': 19,
            'Auditorio': 18,
            'Constituyentes': 15,
            'San Pedro de los Pinos': 16,
            'San Antonio': 17,
            'Mixcoac': 19,
            'Barranca del Muerto': 21,
            'Patriotismo': 12,
            'Chilpancingo': 10,
            'Lázaro Cárdenas': 10,
            'Insurgentes Sur': 21,
            'Hospital 20 de Noviembre': 23,
            'Parque de los Venados': 26,
            'Eje Central': 30},
 'Coyoacán': {'Observatorio': 20,
              'Tacubaya': 17,
              'Juanacatlán': 24,
              'Chapultepec': 21,
              'Sevilla': 20,
              'Insurgentes': 18,
              'Cuauhtémoc': 16,
              'Balderas': 15,
              'Juárez': 16,
              'Niños Héroes': 14,
              'Hospital General': 12,
              'Centro Médico': 11,
              'Etiopía': 9,
              'Eugenia': 7,
              'División del Norte': 5,
              'Zapata': 3,
              'Viveros': 2,
              'Miguel Ángel de Quevedo': 3,
              'Copilco': 6,
              'Universidad': 9,
              'Polanco': 22,
              'Auditorio': 21,
              'Constituyentes': 18,
              'San Pedro de los Pinos': 19,
              'San Antonio': 20,
              'Mixcoac': 22,
              'Barranca del Muerto': 24,
              'Patriotismo': 15,
              'Chilpancingo': 13,
              'Lázaro Cárdenas': 13,
              'Insurgentes Sur': 24,
              'Hospital 20 de Noviembre': 26,
              'Parque de los Venados': 29,
              'Eje Central': 33},
 'Viveros': {'Observatorio': 22,
             'Tacubaya': 19,
             'Juanacatlán': 26,
             'Chapultepec': 23,
             'Sevilla': 22,
             'Insurgentes': 20,
             'Cuauhtémoc': 18,
             'Balderas': 17,
             'Juárez': 18,
             'Niños Héroes': 16,
             'Hospital General': 14,
             'Centro Médico': 13,
             'Etiopía': 11,
             'Eugenia': 9,
             'División del Norte': 7,
             'Zapata': 5,
             'Coyoacán': 2,
             'Miguel Ángel de Quevedo': 1,
             'Copilco': 4,
             'Universidad': 7,
             'Polanco': 24,
             'Auditorio': 23,
             'Constituyentes': 20,
             'San Pedro de los Pinos': 21,
             'San Antonio': 22,
             'Mixcoac': 24,
             'Barranca del Muerto': 26,
             'Patriotismo': 17,
             'Chilpancingo': 15,
             'Lázaro Cárdenas': 15,
             'Insurgentes Sur': 26,
             'Hospital 20 de Noviembre': 28,
             'Parque de los Venados': 31,
             'Eje Central': 35},
 'Miguel Ángel de Quevedo': {'Observatorio': 23,
                             'Tacubaya': 20,
                             'Juanacatlán': 27,
                             'Chapultepec': 24,
                             'Sevilla': 23,
                             'Insurgentes': 21,
                             'Cuauhtémoc': 19,
                             'Balderas': 18,
                             'Juárez': 19,
                             'Niños Héroes': 17,
                             'Hospital General': 15,
                             'Centro Médico': 14,
                             'Etiopía': 12,
                             'Eugenia': 10,
                             'División del Norte': 8,
                             'Zapata': 6,
                             'Coyoacán': 3,
                             'Viveros': 1,
                             'Copilco': 3,
                             'Universidad': 6,
                             'Polanco': 25,
                             'Auditorio': 24,
                             'Constituyentes': 21,
                             'San Pedro de los Pinos': 22,
                             'San Antonio': 23,
                             'Mixcoac': 25,
                             'Barranca del Muerto': 27,
                             'Patriotismo': 18,
                             'Chilpancingo': 16,
                             'Lázaro Cárdenas': 16,
                             'Insurgentes Sur': 27,
                             'Hospital 20 de Noviembre': 29,
                             'Parque de los Venados': 32,
                             'Eje Central': 36},
 'Copilco': {'Observatorio': 26,
             'Tacubaya': 23,
             'Juanacatlán': 30,
             'Chapultepec': 27,
             'Sevilla': 26,
             'Insurgentes': 24,
             'Cuauhtémoc': 22,
             'Balderas': 21,
             'Juárez': 22,
             'Niños Héroes': 20,
             'Hospital General': 18,
             'Centro Médico': 17,
             'Etiopía': 15,
             'Eugenia': 13,
             'División del Norte': 11,
             'Zapata': 9,
             'Coyoacán': 6,
             'Viveros': 4,
             'Miguel Ángel de Quevedo': 3,
             'Universidad': 3,
             'Polanco': 28,
             'Auditorio': 27,
             'Constituyentes': 24,
             'San Pedro de los Pinos': 25,
             'San Antonio': 26,
             'Mixcoac': 28,
             'Barranca del Muerto': 30,
             'Patriotismo': 21,
             'Chilpancingo': 19,
             'Lázaro Cárdenas': 19,
             'Insurgentes Sur': 30,
             'Hospital 20 de Noviembre': 32,
             'Parque de los Venados': 35,
             'Eje Central': 39},
 'Universidad': {'Observatorio': 29,
                 'Tacubaya': 26,
                 'Juanacatlán': 33,
                 'Chapultepec': 30,
                 'Sevilla': 29,
                 'Insurgentes': 27,
                 'Cuauhtémoc': 25,
                 'Balderas': 24,
                 'Juárez': 25,
                 'Niños Héroes': 23,
                 'Hospital General': 21,
                 'Centro Médico': 20,
                 'Etiopía': 18,
                 'Eugenia': 16,
                 'División del Norte': 14,
                 'Zapata': 12,
                 'Coyoacán': 9,
                 'Viveros': 7,
                 'Miguel Ángel de Quevedo': 6,
                 'Copilco': 3,
                 'Polanco': 31,
                 'Auditorio': 30,
                 'Constituyentes': 27,
                 'San Pedro de los Pinos': 28,
                 'San Antonio': 29,
                 'Mixcoac': 31,
                 'Barranca del Muerto': 33,
                 'Patriotismo': 24,
                 'Chilpancingo': 22,
                 'Lázaro Cárdenas': 22,
                 'Insurgentes Sur': 33,
                 'Hospital 20 de Noviembre': 35,
                 'Parque de los Venados': 38,
                 'Eje Central': 42},
 'Polanco': {'Observatorio': 8,
             'Tacubaya': 5,
             'Juanacatlán': 12,
             'Chapultepec': 17,
             'Sevilla': 18,
             'Insurgentes': 18,
             'Cuauhtémoc': 16,
             'Balderas': 15,
             'Juárez': 16,
             'Niños Héroes': 14,
             'Hospital General': 12,
             'Centro Médico': 11,
             'Etiopía': 13,
             'Eugenia': 15,
             'División del Norte': 17,
             'Zapata': 19,
             'Coyoacán': 22,
             'Viveros': 24,
             'Miguel Ángel de Quevedo': 25,
             'Copilco': 28,
             'Universidad': 31,
             'Auditorio': 1,
             'Constituyentes': 4,
             'San Pedro de los Pinos': 7,
             'San Antonio': 8,
             'Mixcoac': 10,
             'Barranca del Muerto': 12,
             'Patriotismo': 7,
             'Chilpancingo': 9,
             'Lázaro Cárdenas': 13,
             'Insurgentes Sur': 12,
             'Hospital 20 de Noviembre': 14,
             'Parque de los Venados': 17,
             'Eje Central': 21},
 'Auditorio': {'Observatorio': 7,
               'Tacubaya': 4,
               'Juanacatlán': 11,
               'Chapultepec': 16,
               'Sevilla': 17,
               'Insurgentes': 17,
               'Cuauhtémoc': 15,
               'Balderas': 14,
               'Juárez': 15,
               'Niños Héroes': 13,
               'Hospital General': 11,
               'Centro Médico': 10,
               'Etiopía': 12,
               'Eugenia': 14,
               'División del Norte': 16,
               'Zapata': 18,
               'Coyoacán': 21,
               'Viveros': 23,
               'Miguel Ángel de Quevedo': 24,
               'Copilco': 27,
               'Universidad': 30,
               'Polanco': 1,
               'Constituyentes': 3,
               'San Pedro de los Pinos': 6,
               'San Antonio': 7,
               'Mixcoac': 9,
               'Barranca del Muerto': 11,
               'Patriotismo': 6,
               'Chilpancingo': 8,
               'Lázaro Cárdenas': 12,
               'Insurgentes Sur': 11,
               'Hospital 20 de Noviembre': 13,
               'Parque de los Venados': 16,
               'Eje Central': 20},
 'Constituyentes': {'Observatorio': 4,
                    'Tacubaya': 1,
                    'Juanacatlán': 8,
                    'Chapultepec': 13,
                    'Sevilla': 14,
                    'Insurgentes': 14,
                    'Cuauhtémoc': 12,
                    'Balderas': 11,
                    'Juárez': 12,
                    'Niños Héroes': 10,
                    'Hospital General': 8,
                    'Centro Médico': 7,
                    'Etiopía': 9,
                    'Eugenia': 11,
                    'División del Norte': 13,
                    'Zapata': 15,
                    'Coyoacán': 18,
                    'Viveros': 20,
                    'Miguel Ángel de Quevedo': 21,
                    'Copilco': 24,
                    'Universidad': 27,
                    'Polanco': 4,
                    'Auditorio': 3,
                    'San Pedro de los Pinos': 3,
                    'San Antonio': 4,
                    'Mixcoac': 6,
                    'Barranca del Muerto': 8,
                    'Patriotismo': 3,
                    'Chilpancingo': 5,
                    'Lázaro Cárdenas': 9,
                    'Insurgentes Sur': 8,
                    'Hospital 20 de Noviembre': 10,
                    'Parque de los Venados': 13,
                    'Eje Central': 17},
 'San Pedro de los Pinos': {'Observatorio': 5,
                            'Tacubaya': 2,
                            'Juanacatlán': 9,
                            'Chapultepec': 14,
                            'Sevilla': 15,
                            'Insurgentes': 15,
                            'Cuauhtémoc': 13,
                            'Balderas': 12,
                            'Juárez': 13,
                            'Niños Héroes': 11,
                            'Hospital General': 9,
                            'Centro Médico': 8,
                            'Etiopía': 10,
                            'Eugenia': 12,
                            'División del Norte': 14,
                            'Zapata': 16,
                            'Coyoacán': 19,
                            'Viveros': 21,
                            'Miguel Ángel de Quevedo': 22,
                            'Copilco': 25,
                            'Universidad': 28,
                            'Polanco': 7,
                            'Auditorio': 6,
                            'Constituyentes': 3,
                            'San Antonio': 1,
                            'Mixcoac': 3,
                            'Barranca del Muerto': 5,
                            'Patriotismo': 4,
                            'Chilpancingo': 6,
                            'Lázaro Cárdenas': 10,
                            'Insurgentes Sur': 5,
                            'Hospital 20 de Noviembre': 7,
                            'Parque de los Venados': 10,
                            'Eje Central': 14},
 'San Antonio': {'Observatorio': 6,
                 'Tacubaya': 3,
                 'Juanacatlán': 10,
                 'Chapultepec': 15,
                 'Sevilla': 16,
                 'Insurgentes': 16,
                 'Cuauhtémoc': 14,
                 'Balderas': 13,
                 'Juárez': 14,
                 'Niños Héroes': 12,
                 'Hospital General': 10,
                 'Centro Médico': 9,
                 'Etiopía': 11,
                 'Eugenia': 13,
                 'División del Norte': 15,
                 'Zapata': 17,
                 'Coyoacán': 20,
                 'Viveros': 22,
                 'Miguel Ángel de Quevedo': 23,
                 'Copilco': 26,
                 'Universidad': 29,
                 'Polanco': 8,
                 'Auditorio': 7,
                 'Constituyentes': 4,
                 'San Pedro de los Pinos': 1,
                 'Mixcoac': 2,
                 'Barranca del Muerto': 4,
                 'Patriotismo': 5,
                 'Chilpancingo': 7,
                 'Lázaro Cárdenas': 11,
                 'Insurgentes Sur': 4,
                 'Hospital 20 de Noviembre': 6,
                 'Parque de los Venados': 9,
                 'Eje Central': 13},
 'Mixcoac': {'Observatorio': 8,
             'Tacubaya': 5,
             'Juanacatlán': 12,
             'Chapultepec': 17,
             'Sevilla': 18,
             'Insurgentes': 18,
             'Cuauhtémoc': 16,
             'Balderas': 15,
             'Juárez': 16,
             'Niños Héroes': 14,
             'Hospital General': 12,
             'Centro Médico': 11,
             'Etiopía': 13,
             'Eugenia': 15,
             'División del Norte': 17,
             'Zapata': 19,
             'Coyoacán': 22,
             'Viveros': 24,
             'Miguel Ángel de Quevedo': 25,
             'Copilco': 28,
             'Universidad': 31,
             'Polanco': 10,
             'Auditorio': 9,
             'Constituyentes': 6,
             'San Pedro de los Pinos': 3,
             'San Antonio': 2,
             'Barranca del Muerto': 2,
             'Patriotismo': 7,
             'Chilpancingo': 9,
             'Lázaro Cárdenas': 13,
             'Insurgentes Sur': 2,
             'Hospital 20 de Noviembre': 4,
             'Parque de los Venados': 7,
             'Eje Central': 11},
 'Barranca del Muerto': {'Observatorio': 10,
                         'Tacubaya': 7,
                         'Juanacatlán': 14,
                         'Chapultepec': 19,
                         'Sevilla': 20,
                         'Insurgentes': 20,
                         'Cuauhtémoc': 18,
                         'Balderas': 17,
                         'Juárez': 18,
                         'Niños Héroes': 16,
                         'Hospital General': 14,
                         'Centro Médico': 13,
                         'Etiopía': 15,
                         'Eugenia': 17,
                         'División del Norte': 19,
                         'Zapata': 21,
                         'Coyoacán': 24,
                         'Viveros': 26,
                         'Miguel Ángel de Quevedo': 27,
                         'Copilco': 30,
                         'Universidad': 33,
                         'Polanco': 12,
                         'Auditorio': 11,
                         'Constituyentes': 8,
                         'San Pedro de los Pinos': 5,
                         'San Antonio': 4,
                         'Mixcoac': 2,
                         'Patriotismo': 9,
                         'Chilpancingo': 11,
                         'Lázaro Cárdenas': 15,
                         'Insurgentes Sur': 4,
                         'Hospital 20 de Noviembre': 6,
                         'Parque de los Venados': 9,
                         'Eje Central': 13},
 'Patriotismo': {'Observatorio': 5,
                 'Tacubaya': 2,
                 'Juanacatlán': 9,
                 'Chapultepec': 14,
                 'Sevilla': 13,
                 'Insurgentes': 11,
                 'Cuauhtémoc': 9,
                 'Balderas': 8,
                 'Juárez': 9,
                 'Niños Héroes': 7,
                 'Hospital General': 5,
                 'Centro Médico': 4,
                 'Etiopía': 6,
                 'Eugenia': 8,
                 'División del Norte': 10,
                 'Zapata': 12,
                 'Coyoacán': 15,
                 'Viveros': 17,
                 'Miguel Ángel de Quevedo': 18,
                 'Copilco': 21,
                 'Universidad': 24,
                 'Polanco': 7,
                 'Auditorio': 6,
                 'Constituyentes': 3,
                 'San Pedro de los Pinos': 4,
                 'San Antonio': 5,
                 'Mixcoac': 7,
                 'Barranca del Muerto': 9,
                 'Chilpancingo': 2,
                 'Lázaro Cárdenas': 6,
                 'Insurgentes Sur': 9,
                 'Hospital 20 de Noviembre': 11,
                 'Parque de los Venados': 14,
                 'Eje Central': 18},
 'Chilpancingo': {'Observatorio': 7,
                  'Tacubaya': 4,
                  'Juanacatlán': 11,
                  'Chapultepec': 12,
                  'Sevilla': 11,
                  'Insurgentes': 9,
                  'Cuauhtémoc': 7,
                  'Balderas': 6,
                  'Juárez': 7,
                  'Niños Héroes': 5,
                  'Hospital General': 3,
                  'Centro Médico': 2,
                  'Etiopía': 4,
                  'Eugenia': 6,
                  'División del Norte': 8,
                  'Zapata': 10,
                  'Coyoacán': 13,
                  'Viveros': 15,
                  'Miguel Ángel de Quevedo': 16,
                  'Copilco': 19,
                  'Universidad': 22,
                  'Polanco': 9,
                  'Auditorio': 8,
                  'Constituyentes': 5,
                  'San Pedro de los Pinos': 6,
                  'San Antonio': 7,
                  'Mixcoac': 9,
                  'Barranca del Muerto': 11,
                  'Patriotismo': 2,
                  'Lázaro Cárdenas': 4,
                  'Insurgentes Sur': 11,
                  'Hospital 20 de Noviembre': 13,
                  'Parque de los Venados': 16,
                  'Eje Central': 20},
 'Lázaro Cárdenas': {'Observatorio': 11,
                     'Tacubaya': 8,
                     'Juanacatlán': 15,
                     'Chapultepec': 12,
                     'Sevilla': 11,
                     'Insurgentes': 9,
                     'Cuauhtémoc': 7,
                     'Balderas': 6,
                     'Juárez': 7,
                     'Niños Héroes': 5,
                     'Hospital General': 3,
                     'Centro Médico': 2,
                     'Etiopía': 4,
                     'Eugenia': 6,
                     'División del Norte': 8,
                     'Zapata': 10,
                     'Coyoacán': 13,
                     'Viveros': 15,
                     'Miguel Ángel de Quevedo': 16,
                     'Copilco': 19,
                     'Universidad': 22,
                     'Polanco': 13,
                     'Auditorio': 12,
                     'Constituyentes': 9,
                     'San Pedro de los Pinos': 10,
                     'San Antonio': 11,
                     'Mixcoac': 13,
                     'Barranca del Muerto': 15,
                     'Patriotismo': 6,
                     'Chilpancingo': 4,
                     'Insurgentes Sur': 15,
                     'Hospital 20 de Noviembre': 17,
                     'Parque de los Venados': 20,
                     'Eje Central': 24},
 'Insurgentes Sur': {'Observatorio': 10,
                     'Tacubaya': 7,
                     'Juanacatlán': 14,
                     'Chapultepec': 19,
                     'Sevilla': 20,
                     'Insurgentes': 20,
                     'Cuauhtémoc': 18,
                     'Balderas': 17,
                     'Juárez': 18,
                     'Niños Héroes': 16,
                     'Hospital General': 14,
                     'Centro Médico': 13,
                     'Etiopía': 15,
                     'Eugenia': 17,
                     'División del Norte': 19,
                     'Zapata': 21,
                     'Coyoacán': 24,
                     'Viveros': 26,
                     'Miguel Ángel de Quevedo': 27,
                     'Copilco': 30,
                     'Universidad': 33,
                     'Polanco': 12,
                     'Auditorio': 11,
                     'Constituyentes': 8,
                     'San Pedro de los Pinos': 5,
                     'San Antonio': 4,
                     'Mixcoac': 2,
                     'Barranca del Muerto': 4,
                     'Patriotismo': 9,
                     'Chilpancingo': 11,
                     'Lázaro Cárdenas': 15,
                     'Hospital 20 de Noviembre': 2,
                     'Parque de los Venados': 5,
                     'Eje Central': 9},
 'Hospital 20 de Noviembre': {'Observatorio': 12,
                              'Tacubaya': 9,
                              'Juanacatlán': 16,
                              'Chapultepec': 21,
                              'Sevilla': 22,
                              'Insurgentes': 22,
                              'Cuauhtémoc': 20,
                              'Balderas': 19,
                              'Juárez': 20,
                              'Niños Héroes': 18,
                              'Hospital General': 16,
                              'Centro Médico': 15,
                              'Etiopía': 17,
                              'Eugenia': 19,
                              'División del Norte': 21,
                              'Zapata': 23,
                              'Coyoacán': 26,
                              'Viveros': 28,
                              'Miguel Ángel de Quevedo': 29,
                              'Copilco': 32,
                              'Universidad': 35,
                              'Polanco': 14,
                              'Auditorio': 13,
                              'Constituyentes': 10,
                              'San Pedro de los Pinos': 7,
                              'San Antonio': 6,
                              'Mixcoac': 4,
                              'Barranca del Muerto': 6,
                              'Patriotismo': 11,
                              'Chilpancingo': 13,
                              'Lázaro Cárdenas': 17,
                              'Insurgentes Sur': 2,
                              'Parque de los Venados': 3,
                              'Eje Central': 7},
 'Parque de los Venados': {'Observatorio': 15,
                           'Tacubaya': 12,
                           'Juanacatlán': 19,
                           'Chapultepec': 24,
                           'Sevilla': 25,
                           'Insurgentes': 25,
                           'Cuauhtémoc': 23,
                           'Balderas': 22,
                           'Juárez': 23,
                           'Niños Héroes': 21,
                           'Hospital General': 19,
                           'Centro Médico': 18,
                           'Etiopía': 20,
                           'Eugenia': 22,
                           'División del Norte': 24,
                           'Zapata': 26,
                           'Coyoacán': 29,
                           'Viveros': 31,
                           'Miguel Ángel de Quevedo': 32,
                           'Copilco': 35,
                           'Universidad': 38,
                           'Polanco': 17,
                           'Auditorio': 16,
                           'Constituyentes': 13,
                           'San Pedro de los Pinos': 10,
                           'San Antonio': 9,
                           'Mixcoac': 7,
                           'Barranca del Muerto': 9,
                           'Patriotismo': 14,
                           'Chilpancingo': 16,
                           'Lázaro Cárdenas': 20,
                           'Insurgentes Sur': 5,
                           'Hospital 20 de Noviembre': 3,
                           'Eje Central': 4},
 'Eje Central': {'Observatorio': 19,
                 'Tacubaya': 16,
                 'Juanacatlán': 23,
                 'Chapultepec': 28,
                 'Sevilla': 29,
                 'Insurgentes': 29,
                 'Cuauhtémoc': 27,
                 'Balderas': 26,
                 'Juárez': 27,
                 'Niños Héroes': 25,
                 'Hospital General': 23,
                 'Centro Médico': 22,
                 'Etiopía': 24,
                 'Eugenia': 26,
                 'División del Norte': 28,
                 'Zapata': 30,
                 'Coyoacán': 33,
                 'Viveros': 35,
                 'Miguel Ángel de Quevedo': 36,
                 'Copilco': 39,
                 'Universidad': 42,
                 'Polanco': 21,
                 'Auditorio': 20,
                 'Constituyentes': 17,
                 'San Pedro de los Pinos': 14,
                 'San Antonio': 13,
                 'Mixcoac': 11,
                 'Barranca del Muerto': 13,
                 'Patriotismo': 18,
                 'Chilpancingo': 20,
                 'Lázaro Cárdenas': 24,
                 'Insurgentes Sur': 9,
                 'Hospital 20 de Noviembre': 7,
                 'Parque de los Venados': 4},
 'Observatorio': {'Tacubaya': 3,
                  'Juanacatlán': 10,
                  'Chapultepec': 15,
                  'Sevilla': 16,
                  'Insurgentes': 16,
                  'Cuauhtémoc': 14,
                  'Balderas': 13,
                  'Juárez': 14,
                  'Niños Héroes': 12,
                  'Hospital General': 10,
                  'Centro Médico': 9,
                  'Etiopía': 11,
                  'Eugenia': 13,
                  'División del Norte': 15,
                  'Zapata': 17,
                  'Coyoacán': 20,
                  'Viveros': 22,
                  'Miguel Ángel de Quevedo': 23,
                  'Copilco': 26,
                  'Universidad': 29,
                  'Polanco': 8,
                  'Auditorio': 7,
                  'Constituyentes': 4,
                  'San Pedro de los Pinos': 5,
                  'San Antonio': 6,
                  'Mixcoac': 8,
                  'Barranca del Muerto': 10,
                  'Patriotismo': 5,
                  'Chilpancingo': 7,
                  'Lázaro Cárdenas': 11,
                  'Insurgentes Sur': 10,
                  'Hospital 20 de Noviembre': 12,
                  'Parque de los Venados': 15,
                  'Eje Central': 19}}

def h(c: int, t: int) -> int:
    if c == t:
        return 0
    
    return m[c][t]
